#!/bin/bash
# Copyright (C) 2019 tribe29 GmbH - License: GNU General Public License v2
# This file is part of Checkmk (https://checkmk.com). It is subject to the terms and
# conditions defined in the file COPYING, which is part of this source code package.

# gets optional socket as argument
function do_query() {

  # we use the sockets full name as instance name:
  INSTANCE_HEADER="[[$2]]"

  # Check if mysqld is running and root password setup
  echo "<<<mysql_ping>>>"
  echo "$INSTANCE_HEADER"
  mysqladmin --defaults-extra-file="$MK_CONFDIR"/mysql.cfg ${1:+--socket="$1"} ping 2>&1 || return

  echo "<<<mysql>>>"
  echo "$INSTANCE_HEADER"
  mysql --defaults-extra-file="$MK_CONFDIR"/mysql.cfg ${1:+--socket="$1"} -sN \
     -e "show global status ; show global variables ;"

  echo "<<<mysql_capacity>>>"
  echo "$INSTANCE_HEADER"
  mysql --defaults-extra-file="$MK_CONFDIR"/mysql.cfg ${1:+--socket="$1"} -sN \
      -e "SELECT table_schema, sum(data_length + index_length), sum(data_free)
         FROM information_schema.TABLES GROUP BY table_schema"

  echo "<<<mysql_slave>>>"
  echo "$INSTANCE_HEADER"
  # do not fail but output nothing if we do not have a slave or do not have the required permission
  mysql --defaults-extra-file="$MK_CONFDIR"/mysql.cfg ${1:+--socket="$1"} -s \
     -e "show slave status\G" || :
}

# if mysqladmin is not retrievable via PATH try to receive mysql home from mysqld process
if ! type mysqladmin >/dev/null 2>&1
then
  mysql_bin=$(ps -C mysqld -o cmd | grep -v CMD | awk '{print $1}')
  if [ -n "${mysql_bin}" ]
  then
    PATH=${PATH}:$(dirname "${mysql_bin}")
  fi
fi

if type mysqladmin >/dev/null
then
  mysql_sockets=$(fgrep -h socket "$MK_CONFDIR"/mysql{.local,}.cfg | sed -ne 's/.*socket=\([^ ]*\).*/\1/p')
  alias=$(fgrep -h alias "$MK_CONFDIR"/mysql{.local,}.cfg | cut -d \" -f2)
  if [ -z "$mysql_sockets" ] ; then
    mysql_sockets=$(ps -fww -C mysqld | grep "socket" | sed -ne 's/.*socket=\([^ ]*\).*/\1/p')
  fi
  if [ -z "$mysql_sockets" ] ; then
    do_query "" "$alias"
  else
    for socket in $mysql_sockets ; do
      if [ -z "$alias" ] ; then
        do_query "$socket" "$socket"
      else
        do_query "$socket" "$alias"
      fi
    done
  fi
fi
